# Starter pipeline
- task: UseNode@1
  inputs:
    version: '12.x'
    checkLatest: true

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Build Ionic 
  inputs:
    script: |
      npm install ionic
      npm install capacitor

      
      ionic build -prod
      npx cap copy android
      

