# Starter pipeline
trigger:
   - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '12.x'
    checkLatest: true
    
- task: CmdLine@2
  inputs:
    script: |
      npm install -g @ionic/cli
      npm install capacitor
      
      ionic build -prod
      npx cap copy android
    workingDirectory: 'mobile'


