trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g @ionic/cli
    ionic build
  workingDirectory: 'mobile'

- script: |
      npm install -g firebase-tools
      firebase deploy --only hosting:okja-beta --token "$(firebaseToken)"
  displayName: 'Deploy to Beta'
  workingDirectory: 'mobile'
  condition: eq('$(deployBeta)',true)